name: contexts

env:
    MY_WORKFLOW_VAR: 'workflow'
    MY_OVERWRITTEN_VAR: 'workflow'

run-name: 06 - Contexts | DEBUB - ${{ inputs.debug }}

on:
  workflow_dispatch:
    inputs:
       debug:
         description: 'Enable debug mode'
         type: boolean
         default: false

jobs:
  echo-data:
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    runs-on: ubuntu-latest
    steps:
      - name: Dsplay Information
        run: |
            echo "Event name: ${{ github.event_name}}"
            echo "Ref: ${{ github.ref }}"
            echo "SHA: ${{ github.sha}}"
            echo  "Actor: ${{ github.actor }}"
            echo "Workflow: ${{ github.workflow}}"
            echo "Run ID: ${{ github.run_id }}"
            echo "Run number: ${{ github.run_number }}"

      
      - name: Retrieve VAriable 
        env:
          MY_VAR: ${{ vars.MY_VAR }}
        run: echo "$MY_VAR"

      - name: Print Env Variables, define overwirtten var here
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "Workflow env: $MY_WORKFLOW_VAR  <retrieve the value of the MY_WORKFLOW_VAR env variable here>"

          echo "Overwritten env: $MY_OVERWRITTEN_VAR <retrieve the value of the MY_OVERWRITTEN_VAR env variable here>"

      - name: Print another env
        run: |
          echo "Workflow env: $MY_WORKFLOW_VAR  <retrieve the value of the MY_WORKFLOW_VAR env variable here>"

          echo "Overwritten env: $MY_OVERWRITTEN_VAR <retrieve the value of the MY_OVERWRITTEN_VAR env variable here>"
          

  echo-data-2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Env Variables
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
      