name: Using Functions

on: 
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo "${{ github.event.pull_request.title }}"
      - name: Print PR labels
        run: |
            cat << EOF
            ${{ toJSON(github.event.pull_request.labels) }}
            EOF
      - name: Test
        if: cancelled()
        run: echo "test"
      - name: Test2
        if: ${{ !cancelled() }}
        run: echo "test2"
      - name: Bug step 
        if: ${{ !cancelled() &&  contains(github.event.pull_request.title, 'fix') }}
        run: echo "I am a bug fix"
      - name: I will execute
        if: ${{ success() }}
        run: echo "I will print if previous step succeded."
      - name: I will be skipped
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails."
      - name: I will execute 
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will execute when any step cancelled"
      
        
