name: Working with matrices

on: 
  workflow_dispatch:

jobs:
  backwars-compatibility:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix: 
        node-version: [24, 26]
        os: 
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node-version: 24
          - os: ubuntu-latest
            node-version: 26
            tag: experimental
    
    steps: 
      - name: Setup node-version
        uses: actions/setup-node@v6
        with: 
          node-version: ${{ matrix.node-version }}
      - name: FAil if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: exit 1

      - name: Perform some tests
        run: |
          echo "Running tests on os ${{ matrix.os }} and node-versionJS ${{ matrix.node-version }}"
          sleep 10
      - name: Upload test results
        run: |
          echo "Uploading test results"
        
  include-example:
    runs-on: ubuntu-latest
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]
        include: 
          - opacity: 50
          - color: red
            shape: triangle

    steps:
      - name: Dummy step
        run: echo "${{ matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{ matrix.opacity }}"

          
