name: Working with matrices

on: 
  workflow_dispatch:

jobs:
  backwars-compatibility:
    runs-on: ${{ matrix.node-version }}
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix: 
        node-version: [24, 26]
        os: 
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node-version: 24
          - os: ubuntu-latest
            node-version: 26
            tag: experimental
    
    steps: 
      - name: Setup node-version
        uses: actions/setup-node@v6
        with: 
          node-version: ${{ matrix.node-version }}
      - name: FAil if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: exit 1

      - name: Perform some tests
        run: |
          echo "Running tests on os ${{ matrix.os }} and node-versionJS ${{ matrix.node-version }}"
          sleep 10
      - name: Upload test results
        run: |
          echo "Uploading test results"
        
